

## compare the cardiac CTS from hESC:C10, E2018 2018 cardiac.a, and E8.25 2019 C8 (not the in vivo and EB C4)
## compare HEP CTS from E8.25 2019 C13, E8.25 2018 endo.b, EB C11,
# and E8.25 2019 C17 (or C8)
library(gplots)
require(dplyr)
library(data.table)
library(ggplot2)
library("gridExtra")
library(ggrepel)
library(ggpubr) # resuired by stat_compare_means()

setwd(here::here("examples", "Shared_Data"))

######################################################
# 3) build IID db GRN --- DO NOT repeat !!!!!!
 ## sdownloaded on 2026 March by Horatio Ai
 # https://iid.ophid.utoronto.ca/
 ################################################################
library(igraph)
library(data.table)

# Downloaded from https://iid.ophid.utoronto.ca/ ; expected at examples/Shared_Data/PPIN/
IID_path <- here::here("examples", "Shared_Data", "PPIN/")
iid <- fread(paste0(IID_path, 'human_annotated_PPIs.txt.gz'), sep="\t", header=TRUE)
dim(iid) #  1675927     344
colnames(iid)
#   [1] "uniprot1"                                                   
#   [2] "uniprot2"                                                   
#   [3] "symbol1"                                                    
#   [4] "symbol2"                                                    
#   [5] "methods"                                                    
#   [6] "pmids"                                                      
#   [7] "db_with_ppi"                                                
#   [8] "evidence_type"                                              
#   [9] "n_methods"                                                  
#  [10] "n_exp_pmids"                                                
#  [11] "n_pred_pmids"                                               
#  [12] "n_pmids"                                                    
#  [13] "detection_type"                                             
#  [14] "co_purified_set_ids"                                        
#  [15] "adipose tissue"                                             
#  [16] "adrenal gland"                                              
#  [17] "amygdala"                                                   
#  [18] "bladder"                                                    
#  [19] "bone"                                                       
#  [20] "bone marrow"                                                
#  [21] "brain"                                                      
#  [22] "cervical tissue"                                            
#  [23] "colon"                                                      
#  [24] "colon mucosa"                                               
#  [25] "dorsal root ganglia"                                        
#  [26] "endometrial tissue"                                         
#  [27] "epidermis"                                                  
#  [28] "heart"                                                      
#  [29] "hypothalamus"                                               
#  [30] "ileum mucosa"                                               
#  [31] "kidney"                                                     
#  [32] "liver"                                                      
#  [33] "lung"                                                       
#  [34] "lymph nodes"                                                
#  [35] "mammary gland"                                              
#  [36] "ovary"                                                      
#  [37] "pancreas"                                                   
#  [38] "pituitary gland"                                            
#  [39] "placenta"                                                   
#  [40] "prostate"                                                   
#  [41] "salivary gland"                                             
#  [42] "skeletal muscle"                                            
#  [43] "skin"                                                       
#  [44] "small intestine"                                            
#  [45] "spleen"                                                     
#  [46] "stomach"                                                    
#  [47] "testes"                                                     
#  [48] "thyroid"                                                    
#  [49] "uterus"                                                     
#  [50] "vulvar tissue"                                              
#  [51] "synovial macrophages"                                       
#  [52] "chondrocytes"                                               
#  [53] "growth plate cartilage"                                     
#  [54] "synovial membrane"                                          
#  [55] "articular cartilage"                                        
#  [56] "B cell, naive"                                              
#  [57] "Monocyte, classical"                                        
#  [58] "Monocyte, non-classical"                                    
#  [59] "NK cell, CD56dim CD16+"                                     
#  [60] "T cell, CD4, memory TREG"                                   
#  [61] "T cell, CD4, naive"                                         
#  [62] "T cell, CD4, naive [activated]"                             
#  [63] "T cell, CD4, naive TREG"                                    
#  [64] "T cell, CD4, TFH"                                           
#  [65] "T cell, CD4, TH1"                                           
#  [66] "T cell, CD4, TH1/17"                                        
#  [67] "T cell, CD4, TH17"                                          
#  [68] "T cell, CD4, TH2"                                           
#  [69] "T cell, CD8, naive"                                         
#  [70] "T cell, CD8, naive [activated]"                             
#  [71] "putamen, left"                                              
#  [72] "superior frontal gyrus, left, medial bank of gyrus"         
#  [73] "middle temporal gyrus, left, inferior bank of gyrus"        
#  [74] "superior frontal gyrus, left, lateral bank of gyrus"        
#  [75] "middle temporal gyrus, left, superior bank of gyrus"        
#  [76] "cingulate gyrus, frontal part, left, inferior bank of gyrus"
#  [77] "pontine nuclei, left"                                       
#  [78] "spinal trigeminal nucleus, left"                            
#  [79] "claustrum, left"                                            
#  [80] "inferior temporal gyrus, left, bank of the its"             
#  [81] "middle frontal gyrus, left, superior bank of gyrus"         
#  [82] "cingulate gyrus, frontal part, left, superior bank of gyrus"
#  [83] "inferior temporal gyrus, left, bank of mts"                 
#  [84] "middle frontal gyrus, left, inferior bank of gyrus"         
#  [85] "lingual gyrus, left, peristriate"                           
#  [86] "superior temporal gyrus, left, inferior bank of gyrus"      
#  [87] "superior temporal gyrus, left, lateral bank of gyrus"       
#  [88] "parahippocampal gyrus, left, lateral bank of gyrus"         
#  [89] "body of caudate nucleus, left"                              
#  [90] "lingual gyrus, left, striate"                               
#  [91] "subiculum, left"                                            
#  [92] "CA1 field, left"                                            
#  [93] "inferior temporal gyrus, left, lateral bank of gyrus"       
#  [94] "superior parietal lobule, left, inferior bank of gyrus"     
#  [95] "head of caudate nucleus, left"                              
#  [96] "precuneus, left, inferior lateral bank of gyrus"            
#  [97] "CA3 field, left"                                            
#  [98] "dentate gyrus, left"                                        
#  [99] "inferior olivary complex, left"                             
# [100] "medial orbital gyrus, left"                                 
# [101] "postcentral gyrus, left, superior lateral aspect of gyrus"  
# [102] "substantia nigra, pars compacta, left"                      
# [103] "CA4 field, left"                                            
# [104] "fusiform gyrus, left, bank of the its"                      
# [105] "gyrus rectus, left"                                         
# [106] "lateral group of nuclei, left, ventral division"            
# [107] "parahippocampal gyrus, left, bank of the cos"               
# [108] "precuneus, left, superior lateral bank of gyrus"            
# [109] "striatum"                                                   
# [110] "telencephalon"                                              
# [111] "putamen"                                                    
# [112] "cerebral nuclei"                                            
# [113] "basal ganglia"                                              
# [114] "cerebral cortex"                                            
# [115] "superior frontal gyrus"                                     
# [116] "frontal lobe"                                               
# [117] "superior frontal gyrus, left"                               
# [118] "middle temporal gyrus, left"                                
# [119] "middle temporal gyrus"                                      
# [120] "temporal lobe"                                              
# [121] "cingulate gyrus, frontal part, left"                        
# [122] "cingulate gyrus, frontal part"                              
# [123] "cingulate gyrus"                                            
# [124] "limbic lobe"                                                
# [125] "basal part of pons"                                         
# [126] "metencephalon"                                              
# [127] "pontine nuclei"                                             
# [128] "pons"                                                       
# [129] "spinal trigeminal nucleus"                                  
# [130] "myelencephalon"                                             
# [131] "claustrum"                                                  
# [132] "inferior temporal gyrus, left"                              
# [133] "inferior temporal gyrus"                                    
# [134] "middle frontal gyrus, left"                                 
# [135] "middle frontal gyrus"                                       
# [136] "occipital lobe"                                             
# [137] "lingual gyrus, left"                                        
# [138] "lingual gyrus"                                              
# [139] "superior temporal gyrus"                                    
# [140] "superior temporal gyrus, left"                              
# [141] "parahippocampal gyrus, left"                                
# [142] "parahippocampal gyrus"                                      
# [143] "body of the caudate nucleus"                                
# [144] "caudate nucleus"                                            
# [145] "hippocampal formation"                                      
# [146] "subiculum"                                                  
# [147] "CA1 field"                                                  
# [148] "parietal lobe"                                              
# [149] "superior parietal lobule, left"                             
# [150] "superior parietal lobule"                                   
# [151] "head of the caudate nucleus"                                
# [152] "precuneus"                                                  
# [153] "precuneus, left"                                            
# [154] "CA3 field"                                                  
# [155] "dentate gyrus"                                              
# [156] "inferior olivary complex"                                   
# [157] "medial orbital gyrus"                                       
# [158] "postcentral gyrus"                                          
# [159] "postcentral gyrus, left"                                    
# [160] "midbrain tegmentum"                                         
# [161] "substantia nigra"                                           
# [162] "substantia nigra, left"                                     
# [163] "mesencephalon"                                              
# [164] "CA4 field"                                                  
# [165] "fusiform gyrus, left"                                       
# [166] "fusiform gyrus"                                             
# [167] "gyrus rectus"                                               
# [168] "dorsal thalamus"                                            
# [169] "thalamus"                                                   
# [170] "diencephalon"                                               
# [171] "lateral group of nuclei, ventral division"                  
# [172] "lateral group of nuclei"                                    
# [173] "1 cell embryo"                                              
# [174] "2 cell embryo"                                              
# [175] "4 cell embryo"                                              
# [176] "8 cell embryo"                                              
# [177] "morula"                                                     
# [178] "blastocyst"                                                 
# [179] "Golgi apparatus"                                            
# [180] "cytoplasm"                                                  
# [181] "cytoskeleton"                                               
# [182] "endoplasmic reticulum"                                      
# [183] "extracellular space"                                        
# [184] "mitochondrion"                                              
# [185] "nuclear matrix"                                             
# [186] "nucleolus"                                                  
# [187] "nucleoplasm"                                                
# [188] "nucleus"                                                    
# [189] "peroxisome"                                                 
# [190] "plasma membrane"                                            
# [191] "vacuole"                                                    
# [192] "breast_cancer"                                              
# [193] "breast_carcinoma"                                           
# [194] "prostate_cancer"                                            
# [195] "prostate_carcinoma"                                         
# [196] "stomach_cancer"                                             
# [197] "large_intestine_cancer"                                     
# [198] "colorectal_cancer"                                          
# [199] "ovarian_cancer"                                             
# [200] "melanoma"                                                   
# [201] "malignant_glioma"                                           
# [202] "lung_carcinoma"                                             
# [203] "stomach_carcinoma"                                          
# [204] "alzheimer_s_disease"                                        
# [205] "leukemia"                                                   
# [206] "non_small_cell_lung_carcinoma"                              
# [207] "urinary_bladder_cancer"                                     
# [208] "colon_carcinoma"                                            
# [209] "coronary_artery_disease"                                    
# [210] "rheumatoid_arthritis"                                       
# [211] "acute_myeloid_leukemia"                                     
# [212] "schizophrenia"                                              
# [213] "obesity"                                                    
# [214] "squamous_cell_carcinoma"                                    
# [215] "colon_cancer"                                               
# [216] "glioblastoma_multiforme"                                    
# [217] "type_2_diabetes_mellitus"                                   
# [218] "pancreatic_carcinoma"                                       
# [219] "adenocarcinoma"                                             
# [220] "liver_cancer"                                               
# [221] "neuroblastoma"                                              
# [222] "diabetes_mellitus"                                          
# [223] "multiple_myeloma"                                           
# [224] "asthma"                                                     
# [225] "lymphoma"                                                   
# [226] "atherosclerosis"                                            
# [227] "hypertension"                                               
# [228] "chronic_lymphocytic_leukemia"                               
# [229] "cancer"                                                     
# [230] "thoracic_cancer"                                            
# [231] "organ_system_cancer"                                        
# [232] "male_reproductive_organ_cancer"                             
# [233] "reproductive_organ_cancer"                                  
# [234] "gastrointestinal_system_cancer"                             
# [235] "intestinal_cancer"                                          
# [236] "female_reproductive_organ_cancer"                           
# [237] "cell_type_cancer"                                           
# [238] "respiratory_system_cancer"                                  
# [239] "lung_cancer"                                                
# [240] "tauopathy"                                                  
# [241] "nervous_system_disease"                                     
# [242] "neurodegenerative_disease"                                  
# [243] "central_nervous_system_disease"                             
# [244] "disease_of_anatomical_entity"                               
# [245] "immune_system_cancer"                                       
# [246] "hematologic_cancer"                                         
# [247] "urinary_system_cancer"                                      
# [248] "artery_disease"                                             
# [249] "cardiovascular_system_disease"                              
# [250] "vascular_disease"                                           
# [251] "bone_disease"                                               
# [252] "bone_inflammation_disease"                                  
# [253] "arthritis"                                                  
# [254] "connective_tissue_disease"                                  
# [255] "musculoskeletal_system_disease"                             
# [256] "myeloid_leukemia"                                           
# [257] "cognitive_disorder"                                         
# [258] "psychotic_disorder"                                         
# [259] "disease_of_mental_health"                                   
# [260] "overnutrition"                                              
# [261] "acquired_metabolic_disease"                                 
# [262] "disease_of_metabolism"                                      
# [263] "nutrition_disease"                                          
# [264] "carcinoma"                                                  
# [265] "astrocytoma"                                                
# [266] "glucose_metabolism_disease"                                 
# [267] "carbohydrate_metabolism_disease"                            
# [268] "pancreatic_cancer"                                          
# [269] "endocrine_gland_cancer"                                     
# [270] "autonomic_nervous_system_neoplasm"                          
# [271] "peripheral_nervous_system_neoplasm"                         
# [272] "nervous_system_cancer"                                      
# [273] "bone_marrow_cancer"                                         
# [274] "myeloid_neoplasm"                                           
# [275] "lower_respiratory_tract_disease"                            
# [276] "respiratory_system_disease"                                 
# [277] "lung_disease"                                               
# [278] "bronchial_disease"                                          
# [279] "obstructive_lung_disease"                                   
# [280] "arteriosclerotic_cardiovascular_disease"                    
# [281] "arteriosclerosis"                                           
# [282] "lymphocytic_leukemia"                                       
# [283] "enzymes"                                                    
# [284] "ion channels"                                               
# [285] "receptors"                                                  
# [286] "transporters"                                               
# [287] "targeted by drugs"                                          
# [288] "drugs targeting both proteins"                              
# [289] "drugs targeting one or both proteins"                       
# [290] "orthologs targeted by drugs"                                
# [291] "drugs targeting orthologs of both proteins"                 
# [292] "drugs targeting orthologs of one or both proteins"          
# [293] "alpaca"                                                     
# [294] "cat"                                                        
# [295] "chicken"                                                    
# [296] "cow"                                                        
# [297] "dog"                                                        
# [298] "duck"                                                       
# [299] "fly"                                                        
# [300] "guinea_pig"                                                 
# [301] "horse"                                                      
# [302] "mouse"                                                      
# [303] "pig"                                                        
# [304] "rabbit"                                                     
# [305] "rat"                                                        
# [306] "sheep"                                                      
# [307] "turkey"                                                     
# [308] "worm"                                                       
# [309] "yeast"                                                      
# [310] "in_complex"                                                 
# [311] "complexes with both proteins"                               
# [312] "complexes with one or both proteins"                        
# [313] "directed"                                                   
# [314] "bidirected"                                                 
# [315] "directions"                                                 
# [316] "direction information"                                      
# [317] "docking_link"                                               
# [318] "stable"                                                     
# [319] "transient"                                                  
# [320] "mutation effects summary"                                   
# [321] "# of causing mutations"                                     
# [322] "# of decreasing mutations"                                  
# [323] "# of decreasing rate mutations"                             
# [324] "# of decreasing strength mutations"                         
# [325] "# of disrupting mutations"                                  
# [326] "# of disrupting rate mutations"                             
# [327] "# of disrupting strength mutations"                         
# [328] "# of increasing mutations"                                  
# [329] "# of increasing rate mutations"                             
# [330] "# of increasing strength mutations"                         
# [331] "# of no effect mutations"                                   
# [332] "# of unknown effect mutations"                              
# [333] "causing mutations"                                          
# [334] "decreasing mutations"                                       
# [335] "decreasing rate mutations"                                  
# [336] "decreasing strength mutations"                              
# [337] "disrupting mutations"                                       
# [338] "disrupting rate mutations"                                  
# [339] "disrupting strength mutations"                              
# [340] "increasing mutations"                                       
# [341] "increasing rate mutations"                                  
# [342] "increasing strength mutations"                              
# [343] "no effect mutations"                                        
# [344] "unknown effect mutations"                                  

# focus on human_mouse Conservation  edges
table(iid$mouse)
#       0       1 
#  144914 1531013 
iid <- iid[mouse == 1];

# add weight based on the number of experimental publications
iid[, n_exp_pmids := as.integer(n_exp_pmids)]
iid[is.na(n_exp_pmids), n_exp_pmids := 0L]
hist(log10(iid$n_exp_pmids), 100, main='wdighting IID PPINS')
dev.copy2pdf(file='hist_iid_n_exp_pmid.pdf')

iid[, w := fifelse(n_exp_pmids >= 100L, 1000, n_exp_pmids * 10) / 1000] # normalize to 0-1

edges <- iid[, .(
  from   = as.character(symbol1),
  to     = as.character(symbol2),
  weight = as.numeric(w)
)]

edges <- edges[!is.na(from) & from != "" & !is.na(to) & to != ""]
edges <- edges[from != to]

edges[, `:=`(
  u = pmin(from, to),
  v = pmax(from, to)
)]

edges <- edges[, .(weight = max(weight, na.rm = TRUE)), by = .(u, v)]

g_iid_global <- graph_from_data_frame(
  edges[, .(from = u, to = v, weight)],
  directed = FALSE
)

(cat("Built g_iid_global:", igraph::vcount(g_iid_global), "nodes,", igraph::ecount(g_iid_global), "edges\n"))
#Built g_iid_global: 17182 nodes, 1517715 edges
saveRDS(g_iid_global, file='iid2025_human_mouse_conserved_global.rds')
  
length(V(g_iid_global))  #[1] 17182
length(E(g_iid_global))  # [1] 1517715
